### ISSUE TITLE
HN platform update 20151110T123936Z - svcs check failed

### ISSUE THREAD

**Issue by andrewbates09** [joyent/sdc-cloud-analytics#1]
Upgrading HN from 20151029 to 20151110 when all of a sudden (post reboot, on check-health) the global zone was not coming back up.

#### Update HN
```
sdcadm self-update
sdcadm platform install --latest
sdcadm platform set-default --latest
reboot
```

#### Health Check
```
----------------------------------------------------------------
[root@headnode (triton-alpha) ~]# sdc-healthcheck
ZONE                                 STATE           AGENT               STATUS
global                               running         -                  svc-err
----------------------------------------------------------------
[root@headnode (triton-alpha) ~]# sdcadm check-health
INSTANCE                              SERVICE     HOSTNAME  ALIAS                HEALTHY
00000000-0000-0000-0000-0cc47a1e5220  global      headnode  global               false
00000000-0000-0000-0000-0cc47a1e5220 SMF svcs check failed: stdout: svc:/smartdc/agent/ca/cainstsvc:default (Cloud Analytics Instrumenter Service)
 State: maintenance since November 10, 2015 09:31:45 PM UTC
Reason: Restarting too quickly.
   See: http://illumos.org/msg/SMF-8000-L5
   See: /var/svc/log/smartdc-agent-ca-cainstsvc:default.log
Impact: This service is not running.
sdcadm check-health: error: Some instances appear unhealthy
```

#### Service check
```
[root@headnode (triton-alpha) ~]# svcs -Zxv
svc:/smartdc/agent/ca/cainstsvc:default (Cloud Analytics Instrumenter Service)
  Zone: global
 State: maintenance since November 10, 2015 11:09:40 PM UTC
Reason: Restarting too quickly.
   See: http://illumos.org/msg/SMF-8000-L5
   See: /var/svc/log/smartdc-agent-ca-cainstsvc:default.log
Impact: This service is not running.
```

#### Log check
```
[root@headnode (triton-alpha) ~]# less /var/svc/log/smartdc-agent-ca-cainstsvc\:default.log

[2015-11-10 21:31:38.868 UTC] CRIT   CA PANIC: panic due to uncaught exception: EXCEPTION: AssertionError: AssertionError: "undefined" == true
    at new caProcDataCache (/opt/smartdc/agents/lib/node_modules/cabase/lib/ca/ca-proc.js:111:2)
    at /opt/smartdc/agents/lib/node_modules/cabase/cmd/cainst/modules/proc.js:35:19
    at ChildProcess.<anonymous> (/opt/smartdc/agents/lib/node_modules/cabase/lib/ca/ca-proc.js:92:4)
    at ChildProcess.emit (events.js:70:17)
    at maybeExit (child_process.js:360:16)
    at Process.onexit (child_process.js:396:5)
[2015-11-10 21:31:38.869 UTC] CRIT   writing core dump to /opt/smartdc/agents/lib/node_modules/cabase/cacore.3414
[2015-11-10 21:31:38.910 UTC] CRIT   finished writing core dump
[ Nov 10 21:31:38 Stopping because all processes in service exited. ]
[ Nov 10 21:31:38 Executing stop method (:kill). ]
[ Nov 10 21:31:38 Executing start method ("/opt/smartdc/agents/lib/node_modules/cabase/smf/method/canodesvc"). ]
DTRACE_LIBPATH=/opt/smartdc/agents/lib/node_modules/cabase/lib

----------------------------------------------------------------

[2015-11-10 23:09:39.746 UTC] CRIT   CA PANIC: panic due to uncaught exception: EXCEPTION: AssertionError: AssertionError: "undefined" == true
    at new caProcDataCache (/opt/smartdc/agents/lib/node_modules/cabase/lib/ca/ca-proc.js:111:2)
    at /opt/smartdc/agents/lib/node_modules/cabase/cmd/cainst/modules/proc.js:35:19
    at ChildProcess.<anonymous> (/opt/smartdc/agents/lib/node_modules/cabase/lib/ca/ca-proc.js:92:4)
    at ChildProcess.emit (events.js:70:17)
    at maybeExit (child_process.js:360:16)
    at Process.onexit (child_process.js:396:5)
[2015-11-10 23:09:39.747 UTC] CRIT   writing core dump to /opt/smartdc/agents/lib/node_modules/cabase/cacore.5831
[2015-11-10 23:09:39.783 UTC] CRIT   finished writing core dump
[ Nov 10 23:09:39 Stopping because all processes in service exited. ]
[ Nov 10 23:09:39 Executing stop method (:kill). ]
[ Nov 10 23:09:40 Restarting too quickly, changing state to maintenance. ]
```

Overall I'm pretty new to SmartOS/Joyent/SDC, and I pointed in this direction to file a bug and get feedback.  Thoughts on the cause, fixing, and/or clearing this up?

**Comment by bahamat** [comment]
I believe this was caused by commit c110a12.

**Comment by bahamat** [comment]
Filed internally as INTRO-716.

**Comment by rmustacc** [comment]
So, the issue here isn't exactly with the commit that @bahamat indicated, rather that the service in question is not running with it.

So from the start, this failure mode is bad and is caused by https://smartos.org/bugview/INTRO-647. Basically we don't properly handle any ctf2json failure properly and just instead, blow up. This should get fixed. That still, however, leaves the original cause of what happened. Given the platform version, this is almost certainly caused by https://github.com/rmustacc/ctf2json/issues/3. The commit https://github.com/joyent/sdc-cloud-analytics/commit/c110a1220f2b191e3ba50183d161d624575d9e88 updates the version of ctf2json to account for this.

The best course of action here is to update the global zone CA instrumenter agent to a version that includes https://github.com/joyent/sdc-cloud-analytics/commit/c110a1220f2b191e3ba50183d161d624575d9e88.

**Comment by shanesveller** [comment]
@rmustacc are there any docs around updating agents in the GZ that would help correct this on a given headnode?

**Comment by bahamat** [comment]
You can use `sdcadm experimental update-agents`. See the full documentation here: <https://docs.joyent.com/private-cloud/maint-and-upgrades>
